# Generated by Django 3.2.15 on 2022-10-23 18:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('time_to_cook', models.TimeField(default=datetime.time(1, 0))),
                ('complexity', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('recipe_text', models.TextField()),
            ],
        ),
    ]
