# Generated by Django 4.1.7 on 2023-06-26 14:04

import autoslug.fields
from django.db import migrations
import recipes.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from=recipes.models.Recipe.name, unique=True),
        ),
    ]
